export function renderOAuthSuccessHtml(styleNonce: string): string {
	return `<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="color-scheme" content="dark">
	<title>OpenCode - Authentication complete</title>
	<style nonce="${styleNonce}">
		:root {
			color-scheme: dark;
			font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
			font-synthesis: none;
		}

		* {
			box-sizing: border-box;
		}

		body {
			min-width: 320px;
			min-height: 100vh;
			margin: 0;
			display: grid;
			place-items: center;
			padding: 32px 20px;
			background:
				radial-gradient(circle at 50% 0%, rgba(42, 195, 126, 0.12), transparent 38rem),
				#080b0a;
			color: #f2f5f3;
		}

		main {
			width: min(100%, 540px);
		}

		.brand {
			display: flex;
			align-items: center;
			gap: 12px;
			margin: 0 0 18px 4px;
			color: #aab5af;
			font-size: 13px;
			font-weight: 600;
			letter-spacing: 0.08em;
			text-transform: uppercase;
		}

		.brand-mark {
			width: 24px;
			height: 24px;
			display: grid;
			grid-template-columns: repeat(2, 1fr);
			gap: 3px;
			padding: 3px;
			border: 1px solid #405048;
			border-radius: 6px;
		}

		.brand-mark span {
			background: #d9e1dd;
			border-radius: 1px;
		}

		.card {
			position: relative;
			overflow: hidden;
			padding: 44px;
			border: 1px solid #26312c;
			border-radius: 20px;
			background: linear-gradient(145deg, rgba(22, 28, 25, 0.98), rgba(13, 17, 15, 0.98));
			box-shadow: 0 24px 80px rgba(0, 0, 0, 0.45);
		}

		.card::before {
			content: "";
			position: absolute;
			inset: 0 0 auto;
			height: 1px;
			background: linear-gradient(90deg, transparent, rgba(86, 224, 157, 0.7), transparent);
		}

		.success-icon {
			width: 58px;
			height: 58px;
			display: grid;
			place-items: center;
			margin-bottom: 28px;
			border: 1px solid rgba(86, 224, 157, 0.45);
			border-radius: 16px;
			background: rgba(42, 195, 126, 0.1);
			color: #56e09d;
			box-shadow: inset 0 0 28px rgba(42, 195, 126, 0.08);
		}

		.success-icon svg {
			width: 28px;
			height: 28px;
		}

		h1 {
			margin: 0;
			font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
			font-size: clamp(28px, 6vw, 38px);
			font-weight: 650;
			letter-spacing: -0.035em;
			line-height: 1.12;
		}

		.lead {
			margin: 16px 0 0;
			color: #aeb8b3;
			font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
			font-size: 17px;
			line-height: 1.6;
		}

		.status {
			display: flex;
			align-items: center;
			gap: 12px;
			margin-top: 30px;
			padding: 15px 16px;
			border: 1px solid #29362f;
			border-radius: 12px;
			background: #0b100d;
			color: #c9d2cd;
			font-size: 13px;
			line-height: 1.5;
		}

		.status-dot {
			width: 8px;
			height: 8px;
			flex: 0 0 auto;
			border-radius: 50%;
			background: #56e09d;
			box-shadow: 0 0 0 4px rgba(86, 224, 157, 0.1);
		}

		.next-step {
			margin: 24px 0 0;
			color: #7f8c85;
			font-size: 13px;
			line-height: 1.6;
		}

		.next-step strong {
			color: #b9c3be;
			font-weight: 600;
		}

		@media (max-width: 520px) {
			body {
				padding: 24px 16px;
			}

			.card {
				padding: 32px 24px;
				border-radius: 16px;
			}

			.success-icon {
				width: 52px;
				height: 52px;
				margin-bottom: 24px;
			}
		}

		@media (prefers-reduced-motion: reduce) {
			*, *::before, *::after {
				scroll-behavior: auto !important;
				animation-duration: 0.01ms !important;
				animation-iteration-count: 1 !important;
			}
		}
	</style>
</head>
<body>
	<main>
		<div class="brand" aria-label="OpenCode">
			<span class="brand-mark" aria-hidden="true"><span></span><span></span><span></span><span></span></span>
			<span>OpenCode</span>
		</div>

		<section class="card" aria-labelledby="success-title">
			<div class="success-icon" aria-hidden="true">
				<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
					<path d="M5 12.5 9.25 17 19 7" stroke="currentColor" stroke-width="2.25" stroke-linecap="round" stroke-linejoin="round"/>
				</svg>
			</div>

			<h1 id="success-title">Authentication complete</h1>
			<p class="lead">Your OpenAI account is connected securely and ready to use with OpenCode.</p>

			<div class="status" role="status">
				<span class="status-dot" aria-hidden="true"></span>
				<span>Credentials encrypted and stored</span>
			</div>

			<p class="next-step"><strong>You can close this tab.</strong> Return to your terminal to continue.</p>
		</section>
	</main>
</body>
</html>`;
}

// Retained for the standalone HTML artifact generated by the package build.
export const oauthSuccessHtml = renderOAuthSuccessHtml("");
